### ISSUE TITLE
Buildpack builds for Node cloudevents template fail on second run if no node_modules exist

### ISSUE THREAD

**Issue by jramcast** [knative-sandbox/kn-plugin-func#1131] opened 2022-07-20 10:11 UTC
We are experiencing this problem with Node.js functions generated from the `cloudevents` template.

The `kn func build` command generates a working Node.js image in the first execution. However, in subsequent executions, the build command generates a failing image. When we run the second image with `kn func run`, we get this error:

```
Function started on port 8080
⛔ Error: Cannot find module 'cloudevents'
Require stack:
- /workspace/index.js
- /layers/paketo-buildpacks_npm-install/launch-modules/node_modules/faas-js-runtime/bin/cli.js
```

We also noticed that **this problem only happens if we have not previously run `npm ci` locally, meaning that the `node_modules` dir does not exist**.
In this case, the output of the 2nd time we run  `kn func build -v` got our attention, specially those cached layers:

```
Paketo NPM Install Buildpack 0.10.1
  Resolving installation process
    Process inputs:
      node_modules      -> "Not found"
      npm-cache         -> "Not found"
      package-lock.json -> "Found"

    Selected NPM build process: 'npm ci'

  Reusing cached layer /layers/paketo-buildpacks_npm-install/build-modules
  Reusing cached layer /layers/paketo-buildpacks_npm-install/launch-modules
  ```
  
  However, if we run `npm ci` before running `kn func build`, then the selected NPM build process changes to `npm rebuild` and the generated image works.

**Versions**
- OpenShift Serverless: `1.23`
- kn: `v1.2.0`
- kn func: `v0.24.0`

**Steps to reproduce**
- `kn func create -l node -t cloudevents foo`
- `kn func build -p foo`
- `kn func run -p foo` // Works fine
- Modify index.js
- `kn func build -p foo`
- `kn func run -p foo` // Fails

**Comment by lance** [comment] 2022-07-20 14:20
I have now reproduced the issue without using `func` at all. Here is the project

package.json
```json
{
  "name": "bar",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "node index.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "cloudevents": "^6.0.2"
  }
}
```
index.js
```js
var http = require('http');
const { CloudEvent } = require('cloudevents');

//create a server object:
http.createServer(function (req, res) {
  res.write('Hello World!');
  res.end();
}).listen(8080);
```
Create these two files in a directory and run the following steps.
```
pack build --builder gcr.io/paketo-buildpacks/builder:base quay.io/lanceball/bar
docker run --rm -it -p 8080:8080 quay.io/lanceball/bar # works fine
# Modify index.js
pack build --builder gcr.io/paketo-buildpacks/builder:base quay.io/lanceball/bar
docker run --rm -it -p 8080:8080 quay.io/lanceball/bar # Fails with the same error noted above
```

**Comment by lance** [comment] 2022-07-20 15:40
@jramcast thanks for reporting this issue. I have dug into it a bit and determined that the root cause is a bug in the paketo npm-install buildpack, and have opened an issue there. In the meantime, it seems that the bug only occurs when there is no node_modules folder locally. Perhaps for the time being, you can include an `npm ci` in your local workflow. Sorry about the inconvenience.

**Comment by jramcast** [comment] 2022-07-21 07:08
@lance thanks for the quick response. Yes, installing the dependencies fixed the issue for us.

**Comment by salaboy** [comment] 2022-07-21 16:08
@jramcast  @lance can we close this issue now ?

**Comment by lance** [comment] 2022-07-21 16:12
@salaboy I'd like to keep it open to track as a known issue until the paketobuildpacks/npm-install buildpack provides a fix.

**Comment by lance** [comment] 2022-08-15 21:28
A PR has been submitted for a fix of this today https://github.com/paketo-buildpacks/npm-install/pull/393

**Closed** 2022-08-23 13:25 UTC
Labels: MVP
