### ISSUE TITLE
[feat] Make use of known-to-be-existent stuff on Openshift

### ISSUE THREAD

**Issue by markusthoemmes** [knative-sandbox/kn-plugin-func#196] opened 2020-10-29 15:46 UTC
**Describe the solution you'd like**
I'd love if I wouldn't have to deal with the fact that we're building images when running on Openshift at all. Wouldn't it be cool if one could just do `kn faas deploy` on an Openshift cluster without additional setup (i.e. dockerhub accounts etc.).

We discussed briefly how it's non trivial to talk to the Openshift internal-registry, but maybe we can salvage Openshift builds (and their binary input feature) to build images on the cluster and into the registry on the fly.

**Comment by lance** [comment] 2021-04-21 21:51
@markusthoemmes I think this should be covered by our On Cluster Builds FT - potentially by TP.

**Comment by omerbensaadon** [comment] 2021-11-05 12:57
Checking on this, can this issue be closed?

**Comment by zroubalik** [comment] 2021-11-05 13:32
@omerbensaadon this is still not resolved

**Comment by lkingland** [comment] 2021-11-07 10:53
> Wouldn't it be cool if one could just do kn faas deploy on an Openshift cluster without additional setup (i.e. dockerhub accounts etc.)

Yes.  That is indeed a goal!  For non-openshift as well.

**Comment by lance** [comment] 2021-12-08 19:31
Closing as a duplicate of #620

**Comment by nainaz** [comment] 2021-12-08 19:31
related to #620

**Closed** 2021-12-08 19:31 UTC
