### ISSUE TITLE
brew install/upgrade not working correctly. 

### ISSUE THREAD

**Issue by nainaz** [knative-sandbox/kn-plugin-func#796] opened 2022-01-27 20:50 UTC
brew install kn func installs v 0.18.0 version. 
brew upgrade kn func doesn't update it to the latest package.

**Comment by lance** [comment] 2022-01-27 20:53
Closing as duplicate of https://github.com/knative-sandbox/kn-plugin-func/issues/794

**Closed by lance** 2022-01-27 20:53 UTC
